// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiLBOUHM9Qi1C1avDrmvdrwEifDuV0heg',
    appId: '1:857283437645:web:918e3cd234456880026804',
    messagingSenderId: '857283437645',
    projectId: 'e-commerce-fbf1b',
    authDomain: 'e-commerce-fbf1b.firebaseapp.com',
    databaseURL: 'https://e-commerce-fbf1b-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-fbf1b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBryd9StEmoW-gYI6XOE1U0WxAw-kRDlWA',
    appId: '1:857283437645:android:ee02ce6da92a82ed026804',
    messagingSenderId: '857283437645',
    projectId: 'e-commerce-fbf1b',
    databaseURL: 'https://e-commerce-fbf1b-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-fbf1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiPrVUbact4V-1MMlDEUjsJMU2VIqdDiM',
    appId: '1:857283437645:ios:c179d0f140c21eb4026804',
    messagingSenderId: '857283437645',
    projectId: 'e-commerce-fbf1b',
    databaseURL: 'https://e-commerce-fbf1b-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-fbf1b.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiPrVUbact4V-1MMlDEUjsJMU2VIqdDiM',
    appId: '1:857283437645:ios:1ef5e4817bc468ec026804',
    messagingSenderId: '857283437645',
    projectId: 'e-commerce-fbf1b',
    databaseURL: 'https://e-commerce-fbf1b-default-rtdb.firebaseio.com',
    storageBucket: 'e-commerce-fbf1b.appspot.com',
    iosBundleId: 'com.example.shoppingApp.RunnerTests',
  );
}
